### ISSUE TITLE
Add more validations

### ISSUE THREAD

**Issue by felippepuhle** [entria/formia#5]
**Strings**
- [x] isAlpha
- [x] isEmail
- [x] minLength
- [x] minWords

**Booleans**
- [x] isTrue
- [x] isFalse

**Dates**
- [ ] isValid
- [ ] isFuture
- [ ] isPast
- [ ] isBetween

**Brazil**
- [x] CPF
- [x] Phone

**Comment by jgcmarins** [comment]
Looks good
